### PR TITLE
Use xblock get_mode method to determine completion mode.

### PR DESCRIPTION
**Pull request by jcdyer**
**Description:** A new method was added to XBlockCompletionMode to return the mode, in order to centralize the logic around unspecified completion_mode meaning "completable."

It was just released in XBlock 1.2.2.  This PR puts it to use.

**JIRA:** Tangential to OC-5161

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:** List testing instructions

**Reviewers:**
- [x] @xitij2000
- [x] @jmbowman 

**Merge checklist:**
- [x] All reviewers approved
- [x] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [x] Commits are squashed
- [x] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2892](https://openedx.atlassian.net/browse/OSPR-2892) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@jcdyer  This is great, thank you for your contribution.  @jmbowman  Can you take a look?

**Comment by natabene** [comment]
@jcdyer Please let me know once it is ready (@xitij2000 has reviewed).

**Comment by jcdyer** [comment]
Thanks guys.  @xitij2000 will give it a review soon.

**Comment by edx-webhook** [comment]
@jcdyer 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/completion&entry.867055334=https://github.com/edx/completion/pull/27&entry.1484655318=https://github.com/jcdyer&entry.752974735=2018-09-06+15:40&entry.1917517419=2018-12-21+01:17&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by jcdyer** [comment]
@natabene This is done now.  Thanks to you, @jmbowman, and @xitij2000 for picking it up.

**Pull request merged**
