### PR TITLE
Add new enable_progress_tracking_events switch

### PR DESCRIPTION
**Pull request by toxinu**
**Description:** Add a new switch for https://github.com/edx/edx-platform/pull/25038

**JIRA:** No Jira ticket

**Dependencies:** No dependency.

**Installation instructions:** No installation.

**Testing instructions:** No testing.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @toxinu! I've created [OSPR-5721](https://openedx.atlassian.net/browse/OSPR-5721) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@toxinu Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by toxinu** [comment]
Closing this pull request based on https://github.com/edx/edx-platform/pull/25038 discussion.

**Comment by edx-webhook** [comment]
@toxinu Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/completion&entry.867055334=https://github.com/edx/completion/pull/141&entry.1484655318=https://github.com/toxinu&entry.752974735=2021-04-06+15:28&entry.1917517419=2021-04-30+02:55&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
