### PR TITLE
fix: make sure last completed block key includes course run

### PR DESCRIPTION
**Pull request by Zacharis278**
**Description:** This makes sure we always use the full block key that includes the course run when calling this utility function.

**Related PR:** https://github.com/edx/edx-platform/pull/27046

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Review by Dillon-Dumesnil — APPROVED** [review]

**Comment by Dillon-Dumesnil** [comment]
Before merging, let me think through what needs to happen for the version update though.

**Comment by Zacharis278** [comment]
ok thanks, just updated the version/changelog. Not sure if there's anything else

**Comment by Dillon-Dumesnil** [comment]
> ok thanks, just updated the version/changelog. Not sure if there's anything else

Will just need to create a v4.0.4 tag after you merge so it gets pushed to PyPI. Then the edx-platform PR needing this will need to bump the version to pull this in and you should be set!

**Comment by matthugs** [comment]
👏

**Pull request merged**
