### PR TITLE
v0.1.15 add Oauth2 auth

### PR DESCRIPTION
**Pull request by jcdyer**
**Description:**  This PR adds the Oauth2 authentication to the v1 endpoint.  Note, this is to backport functionality to the 0.1.x release track, because 1.x doesn't currently work on ginkgo.

**JIRA:** BB-754

**Testing instructions:** List testing instructions

1.  Install this version to a solutions devstack.
2.  Grab an Oauth2 token using the terminal:

    ```
    curl -d 'client_id=shell&client_secret=secret&grant_type=password&username=staff&password=edx' http://localhost:8000/oauth2/access_token/
    ```
3.  Make a request using the token and make sure it works correctly:
    ```
    curl -H "Authorization: $TOKEN" -d '{"username":"staff"}' localhost:8000/api/completion/v1/completion-batch
    ```

**Reviewers:**
- [ ] @viadanna 
- [ ] @

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2992](https://openedx.atlassian.net/browse/OSPR-2992) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@jcdyer Is this ready for review?

**Comment by jcdyer** [comment]
This is obsolete now, as the 1.x branch has been made compatible with ginkgo.

**Comment by edx-webhook** [comment]
@jcdyer Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/completion&entry.867055334=https://github.com/edx/completion/pull/40&entry.1484655318=https://github.com/jcdyer&entry.752974735=2019-01-17+14:36&entry.1917517419=2019-03-29+14:12&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
